{
    'name': 'Hospital Managment',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'odoo name',
    'sequence': -100,
    'summary': 'Hospital managment system',
    'description': """Hospital managment system""",
    'depends': ['mail', 'product','report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/patient.tag.csv',
        'views/odoo_playground_view.xml',
        'data/sequence_data.xml',
        'data/mail_template_data.xml',
        'wizard/cancel_appointment.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
        'views/res_config_settings_views.xml',
        'views/operation_view.xml',
        'report/report.xml',
        'report/patient_details_template.xml',
        'report/patient_card.xml',


    ],
    'demo': [],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
